<?php
/**
 * @author TSN-Media Team
 * @copyright Copyright (c) 2018 TSN-Media (https://tsn-media.com)
 * @package TSN_ProductQuestionnaire
 */
?>
<?php /** @var $block TSN\ProductQuestionnaire\Block\Product\ConfigurableOption */ ?>
<div class="swatch-opt">
    <?php if (!empty($block->getColorLabel()) && $block->getColorLabel() !== 'undefined') { ?>
        <span class="swatch-attribute color">
        <span>Color: </span>
        <strong><?php echo $block->getColorLabel() ?></strong>
    </span>&nbsp;&nbsp;
    <?php } ?>
    <?php if (!empty($block->getSizeLabel()) && $block->getSizeLabel() !== 'undefined') { ?>
        <span class="swatch-attribute size">
        <span>Size: </span>
        <strong><?php echo $block->getSizeLabel() ?></strong>
    </span>
    <?php } ?>
</div>
