<?php
/**
 * @author TSN-Media Team
 * @copyright Copyright (c) 2018 TSN-Media (https://tsn-media.com)
 * @package TSN_ProductQuestionnaire
 */
?>
<?php /** @var $block TSN\ProductQuestionnaire\Block\CartInfo */ ?>

<?php
$count = $block->getItemsCount();
$qty = $block->getItemsQty();
$subTotal = $block->getSubTotal();
?>
<div class="ajaxcart-message-cartinfo">
    <p>
        <?php echo __('There are ') ?>
        <a href="<?php echo $block->getUrl('checkout/cart') ?>"><?php echo $qty . __(' items') ?></a>
        <?php echo __(' in your cart.') ?>
    </p>
    <p><?php echo __('Cart Subtotal: ') ?><?php echo $this->helper('TSN\ProductQuestionnaire\Helper\Data')->getPriceWithCurrency($subTotal) ?></p>
</div>
