<?php
/**
 * @author TSN-Media Team
 * @copyright Copyright (c) 2018 TSN-Media (https://tsn-media.com)
 * @package TSN_ProductQuestionnaire
 */

?>
<div class="tsn-ajaxstyle-popup-wrapper" id="tsn-ajaxstyle-popup-wrapper">
    <a id="tsn-ajaxstyle-close" class="tsn-ajaxstyle-close"></a>
    <?php echo $block->getChildHtml('ajaxstyle.popup.popup'); ?>
</div>
<div class="tsn-ajaxstyle-blank" id="tsn-ajaxstyle-blank"></div>
